/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import ReactNativeEtherjs from 'react-native-etherjs';

export default class App extends Component{
  state = {
    status: 'starting',
    message: '--'
  };
  async componentDidMount() {
    const wallet = await ReactNativeEtherjs.fromMnemonic('man comfort firm depend crowd when tuna soon license mass heart extra');
    console.log(wallet);
  }
  render() {
    return (
      <View>
      </View>
    );
  }
}
